chore: bugfix publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -29,35 +29,44 @@ jobs:
           persist-credentials: false
       - uses: hynek/build-and-inspect-python-package@v2
 
-      - name: check
+  check:
+    name: Extra checks
+    needs: [dist]
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+      - uses: actions/download-artifact@v7
+        with:
+          name: Packages
+          path: dist
+
+      - name: Smoke test
         run: |
-          find .
+          uv run --isolated --no-project --with dist/*.whl tests/test_smoke.py
+          uv run --isolated --no-project --with dist/*.tar.gz tests/test_smoke.py
+
+      - name: Check no changelog fragments
+        if: github.event_name == 'release' && github.event.action == 'published'
+        run: |
+          shopt -s nullglob
+          for _ in changelog.d/*.md ; do
+              echo "Error: changelog snippets found"
+              exit 1
+          done
+          echo "Success: no changelog snippets"
         shell: bash
 
-      # # additional checks
-      # - name: Smoke test
-      #   run: |
-      #     uv run --isolated --no-project --with dist/*.whl tests/test_smoke.py
-      #     uv run --isolated --no-project --with dist/*.tar.gz tests/test_smoke.py
-
-      # - name: Check no changelog fragments
-      #   if: github.event_name == 'release' && github.event.action == 'published'
-      #   run: |
-      #     shopt -s nullglob
-      #     for _ in changelog.d/*.md ; do
-      #         echo "Error: changelog snippets found"
-      #         exit 1
-      #     done
-      #     echo "Success: no changelog snippets"
-      #   shell: bash
-
-      # - name: Check version
-      #   if: github.event_name == 'release' && github.event.action == 'published'
-      #   run: |
-      #     uv run --script tools/check_dist_version.py --version ${{ github.event.release.tag_name }} -- dist/*.whl dist/*.tar.gz
+      - name: Check version
+        if: github.event_name == 'release' && github.event.action == 'published'
+        run: |
+          uv run --script tools/check_dist_version.py --version ${{ github.event.release.tag_name }} -- dist/*.whl dist/*.tar.gz
 
   publish:
-    needs: [dist]
+    name: Publish package
+    needs: [check, dist]
     environment:
       name: pypi
     permissions:
